name: CD — Deploy no Render

on:
  workflow_run:
    workflows: ['CI — Jogo da Forca']
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Render CLI
        run: npm install -g @render-com/cli

      - name: Deploy no Render
        run: render deploys create ${{ secrets.RENDER_SERVICE_ID }} --api-key ${{ secrets.RENDER_API_KEY }} --wait
